service: juanjoselescano-creategiftsls

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x



functions:
  create-gift:
    handler: create-gift.handler
    description: 'An API that create new gift'
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:450865910417:juanjoselescano-createGift
